// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uuirkrlxpmfqljfldtqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1aXJrcmx4cG1mcWxqZmxkdHF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDIxMDAsImV4cCI6MjA2NTUxODEwMH0.2ro97JRiAObl3ieJjQTxPiCdsMRNamUFRurQww7qhsQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);